In [ ]:
import pandas as pd

In [ ]:
a = ['anjali', 'panisha', 'dhruvesh', 24]
df = pd.Series(a)
df

0      anjali
1     panisha
2    dhruvesh
3          24
dtype: object

In [ ]:
df = pd.Series(a, index=["name", "name", "name", "age"])
df

name      anjali
name     panisha
name    dhruvesh
age           24
dtype: object

In [ ]:
df = pd.Series(a, index=["Name", "Name", "Name", "Age"])
df

Name      anjali
Name     panisha
Name    dhruvesh
Age           24
dtype: object

In [ ]:
personal = {
    "Name": ["Anjali", "Anjali", "dhruvesh", "juli", "keyur"],
    "Age": [24,24,27,24,24],
    "Gender": ["female", "female", "male", "female", "female"]
}

print(personal)

{'Name': ['Anjali', 'Anjali', 'dhruvesh', 'juli', 'keyur'], 'Age': [24, 24, 27, 24, 24], 'Gender': ['female', 'female', 'male', 'female', 'female']}

In [ ]:
df = pd.DataFrame(personal)
df

       Name  Age  Gender
0    Anjali   24  female
1    Anjali   24  female
2  dhruvesh   27    male
3      juli   24  female
4     keyur   24  female

In [ ]:
print(df.duplicated())

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [ ]:
df1 = df.loc[0]
df1

Name      Anjali
Age           24
Gender    female
Name: 0, dtype: object

In [ ]:
df1 = df.loc[3]
df1

Name        juli
Age           24
Gender    female
Name: 3, dtype: object

In [ ]:
df1 = df.loc[[0,4]]
df1

     Name  Age  Gender
0  Anjali   24  female
4   keyur   24  female

In [ ]:
df = pd.read_csv("/content/Admission_dataset.csv")
df

,Student ID,University ranking,Student's University dropout rate,SOP rating,CGPA,ZIP Code,GRE,Employed,Strong LOR,Have non academic activities,Been abroad,Chanceof admit
0,3746,30,7.73,1,7.31,90640,317,0,0,0,1,0
1,848,49,16.59,3,6.35,94539,297,0,0,0,1,0
2,2556,80,28.86,2,7.12,94143,298,0,0,0,0,0
3,3641,84,32.95,3,5.94,95821,298,1,0,0,0,0
4,4007,80,27.50,3,5.42,92130,296,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
3995,2704,72,24.09,2,6.31,92521,303,1,0,0,0,0
3996,3690,46,13.86,1,6.17,94708,304,1,0,0,0,0
3997,2689,77,27.50,2,5.54,94542,293,0,0,0,1,0
3998,3534,80,28.18,1,5.88,94545,300,0,0,0,0,0
3999,607,39,12.50,2,6.52,91741,294,0,0,0,1,0

In [ ]:
df.head()

,Student ID,University ranking,Student's University dropout rate,SOP rating,CGPA,ZIP Code,GRE,Employed,Strong LOR,Have non academic activities,Been abroad,Chanceof admit
0,3746,30,7.73,1,7.31,90640,317,0,0,0,1,0
1,848,49,16.59,3,6.35,94539,297,0,0,0,1,0
2,2556,80,28.86,2,7.12,94143,298,0,0,0,0,0
3,3641,84,32.95,3,5.94,95821,298,1,0,0,0,0
4,4007,80,27.50,3,5.42,92130,296,0,0,0,1,0

In [ ]:
df.tail()

,Student ID,University ranking,Student's University dropout rate,SOP rating,CGPA,ZIP Code,GRE,Employed,Strong LOR,Have non academic activities,Been abroad,Chanceof admit
3995,2704,72,24.09,2,6.31,92521,303,1,0,0,0,0
3996,3690,46,13.86,1,6.17,94708,304,1,0,0,0,0
3997,2689,77,27.50,2,5.54,94542,293,0,0,0,1,0
3998,3534,80,28.18,1,5.88,94545,300,0,0,0,0,0
3999,607,39,12.50,2,6.52,91741,294,0,0,0,1,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 12 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Student ID                         4000 non-null   int64
 1   University ranking                 4000 non-null   int64
 2   Student's University dropout rate  4000 non-null   float64
 3   SOP rating                         4000 non-null   int64
 4   CGPA                               4000 non-null   float64
 5   ZIP Code                           4000 non-null   int64
 6   GRE                                4000 non-null   int64
 7   Employed                           4000 non-null   int64
 8   Strong LOR                         4000 non-null   int64
 9   Have non academic activities       4000 non-null   int64
 10  Been abroad                        4000 non-null   int64
 11  Chanceof admit                     4000 non-null   int64
dtypes: float64(2), int64(10)
memory usage: 375.1 KB

In [ ]:
df.describe()

,Student ID,University ranking,Student's University dropout rate,SOP rating,CGPA,ZIP Code,GRE,Employed,Strong LOR,Have non academic activities,Been abroad,Chanceof admit
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.00000,4000.000000
mean,2513.380250,59.581500,20.184942,1.865500,6.383407,93137.798500,299.469750,0.290000,0.060000,0.103000,0.58725,0.096000
std,1450.874343,19.871011,7.769693,0.836113,0.959212,2212.759679,8.780539,0.453819,0.237517,0.303997,0.49239,0.294628
min,1.000000,20.000000,5.000000,1.000000,5.000000,9307.000000,290.000000,0.000000,0.000000,0.000000,0.00000,0.000000
25%,1260.750000,42.000000,13.180000,1.000000,5.650000,91775.000000,293.000000,0.000000,0.000000,0.000000,0.00000,0.000000
50%,2520.000000,60.000000,20.000000,2.000000,6.170000,93407.000000,297.000000,0.000000,0.000000,0.000000,1.00000,0.000000
75%,3778.250000,77.000000,26.820000,3.000000,6.900000,94608.000000,302.000000,1.000000,0.000000,0.000000,1.00000,0.000000
max,5000.000000,100.000000,35.000000,3.000000,9.500000,96651.000000,340.000000,1.000000,1.000000,1.000000,1.00000,1.000000

In [ ]:
df1 = df[['University ranking','SOP rating']]
df1

      University ranking  SOP rating
0                     30           1
1                     49           3
2                     80           2
3                     84           3
4                     80           3
...                  ...         ...
3995                  72           2
3996                  46           1
3997                  77           2
3998                  80           1
3999                  39           2

[4000 rows x 2 columns]

In [ ]:
df["Student ID"].fillna(130, inplace = True)
df

,Student ID,University ranking,Student's University dropout rate,SOP rating,CGPA,ZIP Code,GRE,Employed,Strong LOR,Have non academic activities,Been abroad,Chanceof admit
0,3746,30,7.73,1,7.31,90640,317,0,0,0,1,0
1,848,49,16.59,3,6.35,94539,297,0,0,0,1,0
2,2556,80,28.86,2,7.12,94143,298,0,0,0,0,0
3,3641,84,32.95,3,5.94,95821,298,1,0,0,0,0
4,4007,80,27.50,3,5.42,92130,296,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
3995,2704,72,24.09,2,6.31,92521,303,1,0,0,0,0
3996,3690,46,13.86,1,6.17,94708,304,1,0,0,0,0
3997,2689,77,27.50,2,5.54,94542,293,0,0,0,1,0
3998,3534,80,28.18,1,5.88,94545,300,0,0,0,0,0
3999,607,39,12.50,2,6.52,91741,294,0,0,0,1,0

In [ ]:
x = df["Student ID"].mean()

x

2513.38025

In [ ]:
x = df["Student ID"].median()

x

2520.0

In [ ]:
print(df.duplicated())

0       False
1       False
2       False
3       False
4       False
        ...
3995    False
3996    False
3997    False
3998    False
3999    False
Length: 4000, dtype: bool